package com.example.summaryyoupython.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF785A00)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDF9D)
val md_theme_light_onPrimaryContainer = Color(0xFF251A00)
val md_theme_light_secondary = Color(0xFF6B5D3F)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF5E0BB)
val md_theme_light_onSecondaryContainer = Color(0xFF241A04)
val md_theme_light_tertiary = Color(0xFF4A6547)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFCCEBC5)
val md_theme_light_onTertiaryContainer = Color(0xFF072109)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1E1B16)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1E1B16)
val md_theme_light_surfaceVariant = Color(0xFFEDE1CF)
val md_theme_light_onSurfaceVariant = Color(0xFF4D4639)
val md_theme_light_outline = Color(0xFF7F7667)
val md_theme_light_inverseOnSurface = Color(0xFFF7EFE7)
val md_theme_light_inverseSurface = Color(0xFF33302A)
val md_theme_light_inversePrimary = Color(0xFFF2BF48)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF785A00)
val md_theme_light_outlineVariant = Color(0xFFD0C5B4)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFF2BF48)
val md_theme_dark_onPrimary = Color(0xFF3F2E00)
val md_theme_dark_primaryContainer = Color(0xFF5B4300)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDF9D)
val md_theme_dark_secondary = Color(0xFFD8C4A0)
val md_theme_dark_onSecondary = Color(0xFF3A2F15)
val md_theme_dark_secondaryContainer = Color(0xFF52452A)
val md_theme_dark_onSecondaryContainer = Color(0xFFF5E0BB)
val md_theme_dark_tertiary = Color(0xFFB0CFAA)
val md_theme_dark_onTertiary = Color(0xFF1D361C)
val md_theme_dark_tertiaryContainer = Color(0xFF334D31)
val md_theme_dark_onTertiaryContainer = Color(0xFFCCEBC5)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1E1B16)
val md_theme_dark_onBackground = Color(0xFFE9E1D8)
val md_theme_dark_surface = Color(0xFF1E1B16)
val md_theme_dark_onSurface = Color(0xFFE9E1D8)
val md_theme_dark_surfaceVariant = Color(0xFF4D4639)
val md_theme_dark_onSurfaceVariant = Color(0xFFD0C5B4)
val md_theme_dark_outline = Color(0xFF999080)
val md_theme_dark_inverseOnSurface = Color(0xFF1E1B16)
val md_theme_dark_inverseSurface = Color(0xFFE9E1D8)
val md_theme_dark_inversePrimary = Color(0xFF785A00)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFF2BF48)
val md_theme_dark_outlineVariant = Color(0xFF4D4639)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF795A00)